### ISSUE TITLE
Configuration Doc - Meter type in example should be 'sma' rather than 'sunspec'

### ISSUE THREAD

**Issue by PaulSchulz** [longzheng/open-dynamic-export#55]
https://opendynamicexport.com/configuration/meter#sma

The example given for SMA with connected meter says 'sunspec' as the meter type.
- Should this be 'sma'?

**Comment by longzheng** [comment]
Yep you're right, I'll fix up. 

If you happen to be testing it, let me know how it goes. I actually don't have access to an SMA device to test so it was all done from docs alone 😅

**Comment by PaulSchulz** [comment]
Hi Long,

I am just reading through the documentation and code at the moment.

I am not that familiar with TypeScript, but I am slowly working it out. I am trying to get the docker installation working. Looking for a minimal configuration that will allow me to tinker.

(I will send you an email).

**Comment by longzheng** [comment]
Fix doc with https://github.com/longzheng/open-dynamic-export/commit/57bfdc48810f08821efad702c832e1148ccb86b9
