### ISSUE TITLE
Publish limits via MQTT

### ISSUE THREAD

**Issue by longzheng** [longzheng/open-dynamic-export#62]

**Comment by PaulSchulz** [comment]
If possible, it would be useful to have a 'monitor' MQTT topic, similar to 'limiter' and 'site' which publishes/mirrors the controlls that are sent to the inverter devices.

This would allow data to be pushed, rather than HA (as an example) polling the API.

**Comment by longzheng** [comment]
I've done a first pass at https://github.com/longzheng/open-dynamic-export/pull/64 

It publishes something like 
```json
{
    "opModEnergize": {
        "source": "sep2",
        "value": true
    },
    "opModConnect": {
        "source": "sep2",
        "value": true
    },
    "opModExpLimW": {
        "source": "sep2",
        "value": 1500
    },
    "opModImpLimW": {
        "source": "sep2",
        "value": 1500
    }
}
```

**Comment by longzheng** [comment]
Sorry forgot to document you need to add this to the config

```json
    "publish": {
        "mqtt": {
            "host": "mqtt://192.168.1.2",
            "topic": "limits"
        }
    }
```

**Comment by longzheng** [comment]
Docs page https://opendynamicexport.com/configuration/publish
